import workXLogo from "/img/work-x-logo.png";
import courseOne from "/img/Course1.png";
import courseTwo from "/img/Course2.png";
import courseThree from "/img/Course3.png";
import courseFour from "/img/Course4.png";

const courseData = [
  { id: 1, img: courseOne },
  { id: 2, img: courseTwo },
  { id: 3, img: courseThree },
  { id: 4, img: courseFour },
  { id: 5, img: courseOne },
  { id: 6, img: courseTwo },
];

const internshipsData = [
  {
    id: 1,
    title: "Actively Hiring",
    role: "Software Developer Intern",
    company: "Work X",
    location: "Mumbai",
    salary: "8,000",
    duration: "3 Months",
    category: "Big brands",
    type: "Work from home",
  },
  {
    id: 2,
    title: "Actively hiring",
    role: "Software Developer Intern",
    company: "CollegeDekho.com",
    location: "Gurgaon",
    salary: "10,000",
    duration: "3 Months",
    category: "Big brands",
    type: "Work from home",
  },
  {
    id: 3,
    title: "Actively hiring",
    role: "Software Developer Intern",
    company: "Internshala Trainings",
    location: "Gurgaon",
    salary: "18,000",
    duration: "6 Months",
    category: "Engineering",
    type: "Work from home",
  },
  {
    id: 4,
    title: "Actively hiring",
    role: "Software Developer Intern",
    company: "More Retail Private Limited",
    location: "Bangalore",
    salary: "35,000",
    duration: "3 Months",
    category: "Engineering",
    type: "Work from home",
  },
  {
    id: 5,
    title: "Actively hiring",
    role: "Software Developer Intern",
    company: "More Retail Private Limited",
    location: "Bangalore",
    salary: "35,000",
    duration: "3 Months",
    category: "Engineering",
    type: "Work from home",
  },
  {
    id: 6,
    title: "Actively hiring",
    role: "Software Developer Intern",
    company: "More Retail Private Limited",
    location: "Bangalore",
    salary: "35,000",
    duration: "3 Months",
    category: "Engineering",
    type: "Part time",
  },
  {
    id: 7,
    title: "Actively hiring",
    role: "Software Developer Intern",
    company: "More Retail Private Limited",
    location: "Bangalore",
    salary: "35,000",
    duration: "3 Months",
    category: "Engineering",
    type: "Part time",
  },
  {
    id: 8,
    title: "Actively hiring",
    role: "Data Analyst Intern",
    company: "More Retail Private Limited",
    location: "Bangalore",
    salary: "35,000",
    duration: "3 Months",
    category: "Data Science",
    type: "Work from home",
  },
];

const jobsData = [
  {
    id: 1,
    title: "Actively hiring",
    role: "Software Developer",
    company: "XYZ Company",
    location: "Noida",
    salary: "10",
    experienceRequired: "2 Years of experience",
    category: "Big brands",
    type: "Part time",
  },
  {
    id: 2,
    title: "Actively hiring",
    role: "Software Developer",
    company: "XYZ Company",
    location: "Noida",
    salary: "10",
    experienceRequired: "2 Years of experience",
    category: "Engineering",
    type: "Part time",
  },
  {
    id: 3,
    title: "Actively hiring",
    role: "Software Developer",
    company: "XYZ Company",
    location: "Noida",
    salary: "8",
    experienceRequired: "2 Years of experience",
    category: "Engineering",
    type: "Part time",
  },
  {
    id: 4,
    title: "Actively hiring",
    role: "Software Developer",
    company: "XYZ Company",
    location: "Noida",
    salary: "7",
    experienceRequired: "2 Years of experience",
    category: "Engineering",
    type: "Part time",
  },
  {
    id: 5,
    title: "Actively hiring",
    role: "Software Developer",
    company: "XYZ Company",
    location: "Noida",
    salary: "10",
    experienceRequired: "2 Years of experience",
    category: "Engineering",
    type: "Part time",
  },
  {
    id: 6,
    title: "Actively hiring",
    role: "Data Analyst",
    company: "XYZ Company",
    location: "Noida",
    salary: "10",
    experienceRequired: "2 Years of experience",
    category: "Data Science",
    type: "Part time",
  },
  {
    id: 7,
    title: "Actively hiring",
    company: "XYZ Company",
    role: "Software Engineer",
    location: "Noida",
    salary: "10",
    experienceRequired: "2 Years of experience",
    category: "Engineering",
    type: "Part time",
  },
  {
    id: 8,
    title: "Actively hiring",
    company: "XYZ Company",
    role: "Product Manager",
    location: "Noida",
    salary: "10",
    experienceRequired: "2 Years of experience",
    category: "MBA",
    type: "Work from home",
  },
];

const categories = [
  { id: 1, title: "Big brands" },
  { id: 2, title: "Work from home" },
  { id: 3, title: "Part time" },
  { id: 4, title: "MBA" },
  { id: 5, title: "Engineering" },
  { id: 6, title: "Media" },
  { id: 7, title: "Design" },
  { id: 8, title: "Data Science" },
];

export { workXLogo, courseData, internshipsData, categories, jobsData };
